// <auto-generated />
using System;
using BelterLife.Simulation.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BelterLife.Simulation.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BelterLife.Shared.Entities.Asteroid", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsDestroyed")
                        .HasColumnType("boolean")
                        .HasColumnName("is_destroyed");

                    b.Property<float>("Radius")
                        .HasColumnType("real")
                        .HasColumnName("radius");

                    b.Property<float>("RotationOffset")
                        .HasColumnType("real")
                        .HasColumnName("rotation_offset");

                    b.Property<int>("SectorId")
                        .HasColumnType("integer")
                        .HasColumnName("sector_id");

                    b.Property<int>("VertexCount")
                        .HasColumnType("integer")
                        .HasColumnName("vertex_count");

                    b.Property<float>("VelocityX")
                        .HasColumnType("real")
                        .HasColumnName("velocity_x");

                    b.Property<float>("VelocityY")
                        .HasColumnType("real")
                        .HasColumnName("velocity_y");

                    b.Property<long>("X")
                        .HasColumnType("bigint")
                        .HasColumnName("x");

                    b.Property<long>("Y")
                        .HasColumnType("bigint")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_asteroids");

                    b.HasIndex("SectorId")
                        .HasDatabaseName("ix_asteroids_sector_id");

                    b.ToTable("asteroids", (string)null);
                });

            modelBuilder.Entity("BelterLife.Shared.Entities.NpcStation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<int>("SectorId")
                        .HasColumnType("integer")
                        .HasColumnName("sector_id");

                    b.Property<long>("X")
                        .HasColumnType("bigint")
                        .HasColumnName("x");

                    b.Property<long>("Y")
                        .HasColumnType("bigint")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_npc_stations");

                    b.HasIndex("SectorId")
                        .HasDatabaseName("ix_npc_stations_sector_id");

                    b.ToTable("npc_stations", (string)null);
                });

            modelBuilder.Entity("BelterLife.Shared.Entities.Player", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("id");

                    b.Property<int>("Credits")
                        .HasColumnType("integer")
                        .HasColumnName("credits");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<int>("SectorId")
                        .HasColumnType("integer")
                        .HasColumnName("sector_id");

                    b.Property<int>("ShipId")
                        .HasColumnType("integer")
                        .HasColumnName("ship_id");

                    b.HasKey("Id")
                        .HasName("pk_players");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("BelterLife.Shared.Entities.Sector", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<long>("GridX")
                        .HasColumnType("bigint")
                        .HasColumnName("grid_x");

                    b.Property<long>("GridY")
                        .HasColumnType("bigint")
                        .HasColumnName("grid_y");

                    b.Property<bool>("IsGenerated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_generated");

                    b.Property<long>("Seed")
                        .HasColumnType("bigint")
                        .HasColumnName("seed");

                    b.HasKey("Id")
                        .HasName("pk_sectors");

                    b.ToTable("sectors", (string)null);
                });

            modelBuilder.Entity("BelterLife.Shared.Entities.Ship", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<float>("AngularVelocity")
                        .HasColumnType("real")
                        .HasColumnName("angular_velocity");

                    b.Property<float>("Heading")
                        .HasColumnType("real")
                        .HasColumnName("heading");

                    b.Property<string>("PlayerId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("character varying(450)")
                        .HasColumnName("player_id");

                    b.Property<int>("SectorId")
                        .HasColumnType("integer")
                        .HasColumnName("sector_id");

                    b.Property<float>("VelocityX")
                        .HasColumnType("real")
                        .HasColumnName("velocity_x");

                    b.Property<float>("VelocityY")
                        .HasColumnType("real")
                        .HasColumnName("velocity_y");

                    b.Property<long>("X")
                        .HasColumnType("bigint")
                        .HasColumnName("x");

                    b.Property<long>("Y")
                        .HasColumnType("bigint")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_ships");

                    b.HasIndex("PlayerId")
                        .IsUnique()
                        .HasDatabaseName("ix_ships_player_id");

                    b.ToTable("ships", (string)null);
                });

            modelBuilder.Entity("BelterLife.Shared.Entities.Asteroid", b =>
                {
                    b.HasOne("BelterLife.Shared.Entities.Sector", null)
                        .WithMany()
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asteroids_sectors_sector_id");
                });
#pragma warning restore 612, 618
        }
    }
}
